---
version: 0.2
phases:
  pre_build:
    commands:
      - echo "Install Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq And Fixing Perms.."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validating amazon_linux_packer_template.json"
      - ./packer validate amazon_linux_packer_template.json
  build:
    commands:
      - echo "Use The AWS Meta Data API to get AWS Creds.."
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - echo "Request Successful, configure.."
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building HashiCorp Packer template, amazon_linux_packer_template.json"
      - ./packer build amazon_linux_packer_template.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"