---
version: 0.2
phases:
    pre_build:
        commands:
            - echo "Installing Packer.. "
            - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
            - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            - apt-get update && apt-get install -y packer
            - /usr/bin/packer --version
            - echo "Installing jq And Fixing Perms.."
            - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
            - echo "Validating Packer Template"
            - /usr/bin/packer validate ubuntu_18.pkr.hcl
    build:
        commands:
            - echo "Use The AWS Meta Data API to get AWS Creds.."
            - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
            - echo "Request Successful, configure.."
            - aws configure set region $AWS_REGION
            - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
            - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
            - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
            - echo "Building HashiCorp Packer template, ubuntu_18.pkr.hcl"
            - /usr/bin/packer build ubuntu_18.pkr.hcl
    post_build:
        commands:
            - echo "HashiCorp Packer build completed on `date`"
